import Head from 'next/head';

import { Header, Projects, About, Contact } from 'components';

export default function Home() {
  return (
    <div className="mx-auto max-w-5xl">
      <Head>
        <title>Anvaroov - Frontend Developer.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Projects />
      <About />
      <Contact />
    </div>
  );
}
